sudo: true

language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

# Make chrome browser available for testing
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

addons:
  chrome: stable

jobs:
  include:
    - script:
      - yarn start & node build.js --check --count 1 --framework sinuous vanillajs-keyed
      - (cd webdriver-ts && yarn results)
      name: "Benchmark"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master
